name: Android CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - "main"
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Step 3: Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Clean the project
    - name: Clean project
      run: ./gradlew clean

    # Step 5: Build Debug APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # Step 6: Check if Debug APK exists
    - name: Check Debug APK
      run: ls -la app/build/outputs/apk/debug/

    # Step 7: Archive the Debug APK
    - name: Archive Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

  
