name: Android Release CI

on:
  push:
    branches:
      - "main"
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install CMake 3.30.5
      run: sdkmanager --install "cmake;3.30.5"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon --parallel

    - name: Upload APK to GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.ref_name }} app/build/outputs/apk/release/app-release.apk --clobber
